server:
  port: 9700
spring:
  application:
    name: kafka-producer
  cloud:
    stream:
      kafka:
        binder:
          # kafka消息中间件服务器地址，可以多个ip地址，以逗号隔开
          brokers: localhost:9092
          #zk-nodes: localhost:2181
      bindings:
        # 消息通道
        output:
          binder: kafka
          # 消息发往的目的地 即主题topic
          destination: topic-test-210
          group: output-group-1
          # 消息的格式
          content-type: application/json
        # 自定义的消息输出通道
        my-output:
          binder: kafka
          # 消息发往的目的地 即主题topic
          destination: topic-test-220
          group: output-group-2
          # 消息的格式
          content-type: application/json